-- What are the bottom 3 nations in terms of revenue?

-- Not sure about revenue, so based on my assumption, I consider O_TOTALPRICE and L_EXTENDEDPRICE. 
-- And query is written for both.

SELECT DISTINCT DC.C_NATION, SUM(FMO.O_TOTALPRICE) AS REVENUE  
FROM FACT_MODEL_ONE FMO
JOIN DIM_CUSTOMER DC
ON DC.C_CUSTKEY = FMO.C_CUSTKEY
GROUP BY DC.C_NATION
ORDER BY REVENUE ASC;

-- What are the bottom 3 nations in terms of revenue?
SELECT DISTINCT DC.C_NATION, SUM(FMO.L_EXTENDEDPRICE) AS REVENUE
FROM FACT_MODEL_ONE FMO
JOIN DIM_CUSTOMER DC
ON DC.C_CUSTKEY = FMO.C_CUSTKEY
GROUP BY DC.C_NATION
ORDER BY REVENUE ASC;

-- From the top 3 nations based on revenue, what is the most common shipping mode?
SELECT DISTINCT COUNT(DL.L_SHIPMODE) AS SHIPCOUNT, DL.L_SHIPMODE
FROM DIM_LINEITEM DL
	JOIN FACT_MODEL_ONE FMO
	USING(PRIKEY)
	JOIN DIM_CUSTOMER DC
	ON DC.C_CUSTKEY = FMO.C_CUSTKEY
	INNER JOIN 
		(SELECT N.C_NATION
		 FROM (SELECT
			  SUM(FMO.O_TOTALPRICE) AS REVENUE, DC.C_NATION
			  FROM FACT_MODEL_ONE FMO
					JOIN DIM_CUSTOMER DC
					ON DC.C_CUSTKEY = FMO.C_CUSTKEY
				GROUP BY DC.C_NATION
				ORDER BY REVENUE DESC
				LIMIT 3) AS N) 
		 AS NN
ON NN.C_NATION = DC.C_NATION
GROUP BY DL.L_SHIPMODE
ORDER BY SHIPCOUNT DESC;


-- What are the top 5 selling months?
SELECT DOD.O_ORDERMONTH, SUM(FMO.O_TOTALPRICE) AS REVENUE
FROM FACT_MODEL_ONE FMO
JOIN DIM_ORDER_DATE DOD USING (O_ORDERDATE)
GROUP BY DOD.O_ORDERMONTH
ORDER BY REVENUE DESC;


-- Who are the top customer(s) in terms of either revenue?
SELECT DISTINCT DC.C_NAME, FMO.C_CUSTKEY, SUM(FMO.L_EXTENDEDPRICE) AS REVENUE
FROM FACT_MODEL_ONE FMO
JOIN DIM_CUSTOMER DC
ON DC.C_CUSTKEY = FMO.C_CUSTKEY
GROUP BY FMO.C_CUSTKEY
ORDER BY REVENUE DESC;
-- Who are the top customer(s) in terms of either quantity?
SELECT DISTINCT DC.C_NAME, FMO.C_CUSTKEY, SUM(FMO.L_QUANTITY) AS QUANTITY
FROM FACT_MODEL_ONE FMO
JOIN DIM_CUSTOMER DC
ON DC.C_CUSTKEY = FMO.C_CUSTKEY
GROUP BY FMO.C_CUSTKEY
ORDER BY QUANTITY DESC;


-- Compare the sales revenue on a financial year-to-year (01 July to 30 June) basis.
-- To be specific, I'm not able to solve this question, but I tried, so I mentioned below everything, what I have tried. 

SELECT SUM(REVENUE) AS Total, PREVIOUS_YEAR, HALFYEAR
FROM
(SELECT DOD.O_ORDERYEAR, SUM(FMO.O_TOTALPRICE) AS REVENUE,
LAG(DOD.O_ORDERYEAR, 1) OVER(ORDER BY DOD.O_ORDERDATE ASC) AS PREVIOUS_YEAR, 
	CASE 
		WHEN DOD.O_ORDERMONTH > 6 THEN 2
        ELSE  1
	END AS HALFYEAR
FROM FACT_MODEL_ONE FMO
JOIN DIM_ORDER_DATE DOD USING (O_ORDERDATE)
GROUP BY DOD.O_ORDERYEAR, HALFYEAR, DOD.O_ORDERDATE 
ORDER BY DOD.O_ORDERYEAR ASC) 
AS R_TOTAL_HALFYEAR
GROUP BY PREVIOUS_YEAR, HALFYEAR;
